#!/bin/bash

echo "============ Updating packages ==========="

sudo apt update

echo "============= Installing node ============="

sudo apt install npm -y

sudo npm install -g n

sudo n latest

echo "============ Installing neovim ============"

sudo add-apt-repository ppa:neovim-ppa/unstable
sudo apt-get update
sudo apt-get install -y neovim

git clone --depth 1 https://github.com/wbthomason/packer.nvim\
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim

cp -r ~/configs/nvim ~/.config

sudo npm install -g vscode-langservers-extracted
sudo npm install -g typescript
sudo npm install -g typescript-language-server
sudo npm install -g emmet-ls

echo "============ Installing starshipe ============"

curl -sS https://starship.rs/install.sh | sh
echo "eval \"\$(starship init bash)\"" >> ~/.bashrc
