require("plugins")

vim.cmd("set mouse=a")
vim.cmd("set number")
vim.cmd("set nowrap")
vim.cmd("set cursorline")
vim.cmd("set termguicolors")
vim.cmd("set tabstop=2")
vim.cmd("set shiftwidth=2")
vim.cmd("set expandtab")
vim.cmd("set noswapfile")
vim.cmd("set nobackup")
vim.cmd("set nowritebackup")
vim.cmd("set hidden")
vim.cmd("set title")
vim.cmd("set laststatus=3")
vim.cmd("set splitright")
